/* Subject insertion */
Insert into subject (name) values('Physical Science');
Insert into subject (name) values('American Literature');
Insert into subject (name) values('Geometry');
Insert into subject (name) values('World History');
Insert into subject (name) values('French');

/* Professor insertion */
insert into professor (first_name, last_name, birth_date, email, street_number, street_name, postal_code, city, country, price_hours)
values('Martin', 'Vladosk', '1981-07-27', 'mvladosk@lehmancollege.com', 7, 'Turning Lake Chase', 10007, 'New-York', 'United states of America', 18.7);
insert into professor (first_name, last_name, birth_date, email, street_number, street_name, postal_code, city, country, price_hours)
values('Joseph', 'Smith', '1967-02-05', 'jsmith@lehmancollege.com', 212, 'Bright Gate Race', 10007, 'New-York', 'United states of America', 25.3);
insert into professor (first_name, last_name, birth_date, email, street_number, street_name, postal_code, city, country, price_hours)
values('Sophia', 'Velasquez', '1991-01-30', 'svelasquez@lehmancollege.com', 634, 'Auburn Embers Court', 10007, 'New-York', 'United states of America', 16.5);
insert into professor (first_name, last_name, birth_date, email, street_number, street_name, postal_code, city, country, price_hours) 
values('Texas', 'Lee', '1984-03-12', 'tlee@lehmancollege.com', 459, 'Flower Canyon', 10007, 'New-York', 'United states of America', 34.12);
insert into professor (first_name, last_name, birth_date, email, street_number, street_name, postal_code, city, country, price_hours) 
values('Jane', 'Martin', '1972-10-16', 'jmartin@lehmancollege.com', 45, 'Silent Otter Acres ', 10007, 'New-York', 'United states of America', 42.1);

/* Course insertion */
insert into course (subject_id, professor_id, name, description, duration, date)
values(1, 1, 'SCI102: Physical Science', 'Students explore the relationship between matter and energy by investigating force and motion, the structure of atoms, the structure and properties of matter, chemical reactions, and the interactions of energy and matter. Students develop skill in measuring, solving problems, using laboratory apparatuses, following safety procedures, and adhering to experimental procedures. Students focus on inquiry-based learning, with hands-on laboratory investigations and virtual laboratory experiences.', '02:30:00', '2015-07-15 08:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(1, 1, 'SCI403: Physics', 'This course provides a comprehensive survey of all key areas: physical systems, measurement, kinematics, dynamics, momentum, energy, thermodynamics, waves, electricity, and magnetism, and introduces students to modern physics topics such as quantum theory and the atomic nucleus. The course gives students a solid basis to move on to more advanced courses later in their academic careers. The program consists of online instruction, virtual laboratories, and related assessments, plus an associated problem-solving book.', '04:00:00', '2015-07-30 10:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(1, 1, 'SCI404: Honors Physics', 'This advanced course surveys all key areas: physical systems, measurement, kinematics, dynamics, momentum, energy, thermodynamics, waves, electricity, and magnetism, and introduces students to modern physics topics such as quantum theory and the atomic nucleus. Additional honors assignments include debates, research papers, extended collaborative laboratories, and virtual laboratories. The course gives a solid basis for moving on to more advanced college physics courses. The program consists of online instruction, virtual laboratories, and related assessments, plus an associated problem-solving book.', '03:15:00', '2015-09-03 12:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(1, 1, 'SCI106: Physical Science', 'Students explore the relationship between matter and energy by investigating force and motion, the structure of atoms, the structure and properties of matter, chemical reactions, and the interactions of energy and matter. They review strategies for describing and measuring scientific concepts. Diagnostic tests assess students\� current knowledge and generate individualized study plans, so students can focus on topics that need review.', '02:00:00', '2015-08-15 09:00:00');

insert into course (subject_id, professor_id, name, description, duration, date)
values(2, 2, 'ENG102: Literary Analysis and Composition I (Core)', 'In this course, students work on their written and oral communication skills, while strengthening their ability to understand and analyze works of literature, both classic and modern.
Literature: Students read short stories, poetry, drama, novels, essays, and informative articles. The course sharpens reading comprehension skills and engages readers in literary analysis as they consider important human issues and challenging ideas. Students also learn to read for information in nonfiction texts.
Language Skills: Students learn to express their ideas effectively. They sharpen their composition skills through a focus on writing good paragraphs and essays in a variety of genres, such as persuasive and research essays. Students plan, organize, and revise written works in response to feedback on drafts. In grammar, usage, and mechanics lessons, students expand their understanding of parts of speech, phrases and clauses, sentence analysis and structure, agreement, punctuation, and other conventions. Vocabulary lessons build knowledge of Greek and Latin words that form the roots of many English words. Students use word origins and derivations to determine the meaning of new words as they increase their vocabularies.', '04:00:00', '2015-07-14 12:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(2, 2, 'ENG103: Literary Analysis and Composition I (Comprehensive)', 'LITERATURE: Students read a broad array of short stories, poetry, drama, novels, autobiographies, essays, and famous speeches. The course guides students in the close reading and critical analysis of classic works of literature, and helps them appreciate the texts and the contexts in which the works were written. Literary selections range classic works such as Shakespeare\�s Romeo and Juliet to contemporary pieces by authors such as Maya Angelou.
LANGUAGE SKILLS: Students broaden their composition skills by examining model essays in various genres by student and published writers. Through in-depth planning, organizing, drafting, revising, proofreading, and feedback, they hone their writing skills. Students build on their grammar, usage, and mechanics skills with in-depth study of sentence analysis and structure, agreement, and punctuation, reinforced by online activities (Skills Updates). Student vocabularies are enhanced through the study of Greek and Latin roots, improving students\� ability to decipher the meanings of new words.', '03:30:00', '2015-07-20 17:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(2, 2, 'ENG104: Honors Literary Analysis and Composition I', 'K12 High School Literary Analysis and Composition I challenges students to improve their written and oral communication skills, while strengthening their ability to understand and analyze literature in a variety of genres.  Students enrolled in this course will work on independent projects which will enhance their skills and challenge them to consider complex ideas and apply the  knowledge they have learned.
Literature: Students read a broad array of short stories, poetry, drama, novels, autobiographies, essays, and famous speeches. The course guides students in the close reading and critical analysis of classic works of literature, and helps them appreciate the texts and the contexts in which the works were written. Literary selections range from the Greek tragedy Antigone to Shakespeare\�s Romeo and Juliet to contemporary pieces by authors such as Annie Dillard and Maya Angelou.
Language Skills: Students broaden their composition skills by examining model essays in various genres by student and published writers. Through in-depth planning, organizing, drafting, revising, proofreading, and feedback, they hone their writing skills. Students build on their grammar, usage, and mechanics skills with in-depth study of sentence analysis and structure, agreement, and punctuation, reinforced by online activities (Skills Updates). Student vocabularies are enhanced through the study of Greek and Latin root words, improving students\� ability to decipher the meanings of new words.', '04:15:00', '2015-07-30 11:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(2, 2, 'ENG106: Literary Analysis and Composition I', 'Students are able to gain credit if they have previously completed this course but did not successfully earn credit. For each unit, students take a diagnostic test that assesses their current knowledge of fundamental content. The results of these tests help students create individualized study plans.
In the course, students read a variety of literary works to sharpen reading comprehension and literary analysis skills. They review composition skills and expand their understanding of parts of speech, phrases and clauses, sentence analysis and structure, agreement, punctuation, and other conventions. Vocabulary lessons build knowledge of Greek and Latin words that form the roots of many English words.', '02:00:00', '2015-08-16 15:00:00');

insert into course (subject_id, professor_id, name, description, duration, date)
values(3, 3, 'MTH202: Geometry (Core)', 'Students learn to recognize and work with geometric concepts in various contexts. They build on ideas of inductive and deductive reasoning, logic, concepts, and techniques of Euclidean plane and solid geometry and develop an understanding of mathematical structure, method, and applications of Euclidean plane and solid geometry. Students use visualizations, spatial reasoning, and geometric modeling to solve problems. Topics of study include points, lines, and angles; triangles; right triangles; quadrilaterals and other polygons; circles; coordinate geometry; three-dimensional solids; geometric constructions; symmetry; the use of transformations; and non-Euclidean geometries.', '02:00:00', '2015-07-13 17:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(3, 3, 'MTH203: Geometry (Comprehensive)', 'Students learn to recognize and work with geometric concepts in various contexts. They build on ideas of inductive and deductive reasoning, logic, concepts, and techniques of Euclidean plane and solid geometry and develop an understanding of mathematical structure, method, and applications of Euclidean plane and solid geometry. Students use visualizations, spatial reasoning, and geometric modeling to solve problems. Topics of study include points, lines, and angles; triangles; right triangles; quadrilaterals and other polygons; circles; coordinate geometry; three-dimensional solids; geometric constructions; symmetry; the use of transformations; and non-Euclidean geometries.
Compared to MTH202, this course has a more rigorous pace and more challenging assignments and assessments. MTH203 also covers additional topics such biconditionals, rotations of points in a coordinate plane, creating and interpreting truth tables, parametric equations for lines in three dimensions, finding the equation of a circle from three points, input-output tables for logical gates, and several theorems including the Jordan Curve Theorem, Pappus\' Theorem, and Desargues\' Theorem.', '03:15:00', '2015-07-22 14:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(3, 3, 'MTH204: Honors Geometry', 'Students learn to recognize and work with geometric concepts in various contexts. They build on ideas of inductive and deductive reasoning, logic, concepts, and techniques of Euclidean plane and solid geometry and develop an understanding of mathematical structure, method, and applications of Euclidean plane and solid geometry. Students use visualizations, spatial reasoning, and geometric modeling to solve problems. Topics of study include points, lines, and angles; triangles; right triangles; quadrilaterals and other polygons; circles; coordinate geometry; three-dimensional solids; geometric constructions; symmetry; the use of transformations; and non-Euclidean geometries.
This course includes all the topics in MTH203, but has more challenging assignments and includes more optional challenge activities. Each semester also includes an independent honors project.', '04:30:00', '2015-09-04 09:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(3, 3, 'MTH206: Geometry', 'Students are able to gain credit if they have previously completed this course but did not successfully earn credit. For each unit, students take a diagnostic test that assesses their current knowledge of fundamental content. The results of these tests help students create individualized study plans.
Students move at their own pace and then are assessed by computer-scored unit tests for a grade. Teacher-graded assignments are available as optional or for review only. Students review core geometric concepts as they develop sound ideas of inductive and deductive reasoning, logic, concepts, and techniques and applications of Euclidean plane and solid geometry. Students use visualizations, spatial reasoning, and geometric modeling to solve problems. Topics include points, lines, and angles; triangles, polygons, and circles; coordinate geometry; three-dimensional solids; geometric constructions; symmetry; and the use of transformations.', '02:00:00', '2015-08-17 10:00:00');

insert into course (subject_id, professor_id, name, description, duration, date)
values(4, 4, 'HST102: World History (Core)', 'In this survey of world history from prehistoric to modern times, students focus on the key developments and events that have shaped civilization across time. The course is organized chronologically and, within broad eras, regionally. Lessons address developments in religion, philosophy, the arts, science and technology, and political history. The course also introduces geography concepts and skills within the context of the historical narrative. Online lessons and assessments complement World History: Our Human Story, a textbook written and published by K12. Students analyze primary sources and maps, create timelines, and complete other projects� practicing historical thinking and writing skills as they explore the broad themes and big ideas of human history.', '02:30:00', '2015-07-18 12:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(4, 4, 'HST103: World History (Comprehensive)', 'In this comprehensive survey of world history from prehistoric to modern times, students focus in depth on the developments and events that have shaped civilization across time. The course is organized chronologically and, within broad eras, regionally. Lessons address developments in religion, philosophy, the arts, science and technology, and political history. The course also introduces geography concepts and skills within the context of the historical narrative. Online lessons and assessments complement World History: Our Human Story, a textbook written and published by K12. Students are challenged to consider topics in depth as they analyze primary sources and maps, create timelines, and complete other projects� practicing historical thinking and writing skills as they explore the broad themes and big ideas of human history.', '03:15:00', '2015-07-29 18:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(4, 4, 'HST104: Honors World History', 'In this challenging survey of world history from prehistoric to modern times, students focus in depth on the developments and events that have shaped civilization across time. The course is organized chronologically and, within broad eras, regionally. Lessons address developments in religion, philosophy, the arts, science and technology, and political history. The course also introduces geography concepts and skills within the context of the historical narrative. Online lessons and assessments complement World History: Our Human Story, a textbook written and published by K12', '04:00:00', '2015-09-10 16:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(4, 4, 'HST106: World History', 'Students are able to gain credit if they have previously completed this course, but did not successfully earn credit. For each unit, students take a diagnostic test that assesses their current knowledge of fundamental content. The results of these tests help students create individualized study plans. This course traces the development of civilizations around the world from prehistory to the present, with a special emphasis on key periods and primary sources. The course covers major events in world history, including the development and influence of human-geographic relationships, political and social structures, economics, science and technology, and the arts. Students investigate the major religions and belief systems throughout history and learn about the importance of trade and cultural exchange. Other topics include the development of agriculture, the spread of democracy, the rise of nation states, the industrial era, the spread of imperialism, and the issues and conflicts of the twentieth century.', '02:30:00', '2015-08-21 10:00:00');

insert into course (subject_id, professor_id, name, description, duration, date)
values(5, 5, 'WLG110: French I', 'Students begin their introduction to French by focusing on the four key areas of foreign language study: listening, speaking, reading, and writing. The course represents an ideal blend of language learning pedagogy and online learning. Each unit consists of a new vocabulary theme and grammar concept, reading and listening comprehension activities, speaking and writing activities, multimedia cultural presentations, and interactive activities and practices which reinforce vocabulary and grammar. There is a strong emphasis on providing context and conversational examples for the language concepts presented in each unit. Students should expect to be actively engaged in their own language learning, become familiar with common vocabulary terms and phrases, comprehend a wide range of grammar patterns, participate in simple conversations and respond appropriately to basic conversational prompts, analyze and compare cultural practices, products, and perspectives of various French-speaking countries, and take frequent assessments where their language progression can be monitored. The course has been carefully aligned to national standards as set forth by ACTFL (the American Council on the Teaching of Foreign Languages).', '03:00:00', '2015-07-08 09:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(5, 5, 'WLG210: French II', 'Students continue their study of French by further expanding their knowledge of key vocabulary topics and grammar concepts. Students not only begin to comprehend listening and reading passages more fully, but they also start to express themselves more meaningfully in both speaking and writing. Each unit consists of a new vocabulary theme and grammar concept, reading and listening comprehension activities, speaking and writing activities, multimedia cultural presentations, and interactive activities and practices which reinforce vocabulary and grammar. There is a strong emphasis on providing context and conversational examples for the language concepts presented in each unit. Students should expect to be actively engaged in their own language learning, understand common vocabulary terms and phrases, use a wide range of grammar patterns in their speaking and writing, participate in conversations and respond appropriately to conversational prompts, analyze and compare cultural practices, products, and perspectives of various French-speaking countries, and take frequent assessments where their language progression can be monitored. By semester 2, the course is conducted almost entirely in French. The course has been carefully aligned to national standards as set forth by ACTFL (the American Council on the Teaching of Foreign Languages).', '03:00:00', '2015-07-31 15:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(5, 5, 'WLG310: French III', 'Students further deepen their understanding of French by focusing on the three modes of communication: interpretive, interpersonal, and presentational. Each unit consists of a variety of activities which teach the students how to understand more difficult written and spoken passages, to communicate with others through informal speaking and writing interactions, and to express their thoughts and opinions in both formal and informal spoken and written contexts. Students should expect to be actively engaged in their own language learning, use correct vocabulary terms and phrases naturally, incorporate a wide range of grammar concepts consistently and correctly while speaking and writing, participate in conversations covering a wide range of topics, respond appropriately to conversational prompts, analyze and compare cultural practices, products, and perspectives of various French-speaking countries, read and analyze important pieces of literature, and take frequent assessments where their language progression can be monitored. The course is conducted almost entirely in French. The course has been carefully aligned to national standards as set forth by ACTFL (the American Council on the Teaching of Foreign Languages).', '04:00:00', '2015-09-08 13:00:00');
insert into course (subject_id, professor_id, name, description, duration, date)
values(5, 5, 'WLG510: AP French Language and Culture', 'Our online AP French Language course is an advanced language course in which students acquire proficiencies that expand their cognitive, analytical and communicative skills. The AP French Language course prepares them for the AP French exam. It uses as its foundation the three modes of communication (Interpersonal, Interpretive and Presentational) as defined in the Standards for Foreign Language Learning in the 21st Century.
The course is designed as an immersion experience requiring the use of French exclusively. The online learning coach only uses French to communicate with students. In addition, all the reading, listening, speaking and writing is in French.The course is based on the six themes required by the College Board, namely:
Global challenges
Science and technology
Contemporary life
Personal and public identities
Families and communities
Beauty and aesthetics
The course teaches language structures in context and focuses on the development of fluency to convey meaning. Students explore culture in both contemporary and historical contexts to develop an awareness and appreciation of cultural products, practices, and perspectives. The course contains a forum where students share their own opinions and comments and comment on other students\' posts. The course makes great use of the Internet for updated and current material.', '05:00:00', '2015-09-17 14:00:00');